"""v1.3 post-test EXPLORATORY analyses on existing test rows (CPU only).

A1 flip analysis + oracle stability, A2 scratch-states-answer, A3 confidence trajectories,
A4 AUROC of the C0 margin for "C1(32,16) fixes a C0 error", A5 LLaDA C0 vs Qwen3-8B C0.
Paired bootstrap 1000 resamples, seed 1234, 95% percentile CIs; McNemar exact p.

Usage: python scripts/analysis_v13.py  -> results/v13_exploratory.md, results/v13_exploratory.json
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dd.analysis import CELLS13, index_rows  # noqa: E402
from dd.metrics import expected_calibration_error, mcnemar_test, multiclass_brier, negative_log_likelihood  # noqa: E402
from dd.report import load_rows  # noqa: E402

DATASETS = ["boolq", "strategyqa", "arc_c", "jagged"]
MODEL, QWEN = "llada-8b-instruct", "qwen3-8b"
N_BOOT, SEED = 1000, 1234
C0 = ("C0", 0, None)


def f(x, d=3):
    return "n/a" if x is None or (isinstance(x, float) and not np.isfinite(x)) else f"{x:.{d}f}"


def name(cell):
    c, s, t = cell
    return "C0" if c == "C0" else f"{c} {s},{t}"


def boot(stat, n, seed=SEED):
    rng = np.random.default_rng(seed)
    vals = np.array([stat(rng.integers(0, n, n)) for _ in range(N_BOOT)])
    return float(np.quantile(vals, 0.025)), float(np.quantile(vals, 0.975))


def conf(row):
    return max(row["final_probs"].values())


def margin(row):
    p = sorted(row["final_probs"].values(), reverse=True)
    return p[0] - (p[1] if len(p) > 1 else 0.0)


def auroc(scores, labels):
    scores, labels = np.asarray(scores, float), np.asarray(labels, bool)
    pos, neg = scores[labels], scores[~labels]
    if len(pos) == 0 or len(neg) == 0:
        return float("nan")
    order = np.argsort(np.concatenate([pos, neg]), kind="mergesort")
    ranks = np.empty(len(order))
    allv = np.concatenate([pos, neg])[order]
    i = 0
    r = np.arange(1, len(allv) + 1, dtype=float)
    while i < len(allv):  # average ranks for ties
        j = i
        while j + 1 < len(allv) and allv[j + 1] == allv[i]:
            j += 1
        r[i:j + 1] = (i + j + 2) / 2
        i = j + 1
    ranks[order] = r
    return float((ranks[: len(pos)].sum() - len(pos) * (len(pos) + 1) / 2) / (len(pos) * len(neg)))


ANSWER_PATTERNS = [
    re.compile(r"answer\s*(?:is|:)?\s*[\"'(]?\s*([A-E])\b(?![a-z])"),
    re.compile(r"\b(?:option|choice)\s*[\"'(]?\s*([A-E])\b(?![a-z])"),
]
YESNO = re.compile(r"answer\s*(?:is|:)?\s*[\"'(]?\s*(yes|no)\b", re.I)
ANSWER_TEXT = re.compile(r"answer\s*(?:is|:)\s*(.{1,80})", re.I)


def stated_answer(text: str, item: dict) -> str | None:
    """Letter of an explicit answer stated in the scratch (last occurrence), or None."""
    if not text:
        return None
    found = None
    for pat in ANSWER_PATTERNS:
        for m in pat.finditer(text):
            letter = m.group(1)
            if letter in item["letters"]:
                found = (m.start(), letter)
    for m in YESNO.finditer(text):
        word = m.group(1).capitalize()
        if word in item["options"]:
            pos = (m.start(), item["letters"][item["options"].index(word)])
            found = pos if found is None or pos[0] >= found[0] else found
    for m in ANSWER_TEXT.finditer(text):
        tail = m.group(1).strip().lower()
        for letter, option in zip(item["letters"], item["options"]):
            if len(option) > 2 and tail.startswith(option.lower()):
                pos = (m.start(), letter)
                found = pos if found is None or pos[0] >= found[0] else found
    return found[1] if found else None


def main() -> None:
    rows = load_rows(ROOT)
    items = {json.loads(l)["item_id"]: json.loads(l) for l in (ROOT / "results" / "items.jsonl").read_text(encoding="utf-8").splitlines() if l.strip()}
    idx = index_rows(rows, MODEL, "test")
    qidx = index_rows(rows, QWEN, "test")
    out = {"A1": {}, "A1_oracle": {}, "A2": {}, "A3": {}, "A4": {}, "A5": {}}
    L = ["# v1.3 post-test exploratory analyses (test split; exploratory, no confirmatory verdicts)", "",
         "Paired bootstrap (1000 resamples, seed 1234), 95% percentile CIs; McNemar exact p. Generated by `scripts/analysis_v13.py`.", ""]

    # ---------------- A1 flips
    L += ["## A1. Flips vs C0 (LLaDA)", "", "w→r = wrong at C0, right in the cell; r→w = the reverse; net = (w→r − r→w)/n.", ""]
    for ds in DATASETS:
        base = idx[ds][C0]
        L += [f"### {ds}", "", "| cell | n | w→r | r→w | net [CI] | McNemar p |", "|---|---|---|---|---|---|"]
        for cell in CELLS13[1:]:
            other = idx[ds][cell]
            ids = sorted(set(base) & set(other))
            a = np.array([base[i]["correct"] for i in ids], bool)
            b = np.array([other[i]["correct"] for i in ids], bool)
            w2r, r2w = int((~a & b).sum()), int((a & ~b).sum())
            net = (w2r - r2w) / len(ids)
            lo, hi = boot(lambda ix: (b[ix].astype(int) - a[ix].astype(int)).mean(), len(ids))
            p = mcnemar_test(b, a)["p_value_exact"]
            out["A1"][f"{ds}|{name(cell)}"] = {"n": len(ids), "w2r": w2r, "r2w": r2w, "net": net, "lo": lo, "hi": hi, "p": p}
            L.append(f"| {name(cell)} | {len(ids)} | {w2r} | {r2w} | {f(net)} [{f(lo)}, {f(hi)}] | {f(p, 4)} |")
        L.append("")

    L += ["### Oracle stability (escalation must be correct in BOTH C1 and C2 at that budget)", "",
          "Plain oracle: cheapest correct ladder level. Stable oracle: an item counts as fixed at level k only if it is wrong at C0 "
          "and correct in both C1 and C2 at level k's (S, T); otherwise it falls through (and stays wrong if never fixed).", "",
          "| ladder | dataset | C0 acc | oracle acc / NFE | stable oracle acc / NFE | share of headroom kept [CI] |", "|---|---|---|---|---|---|"]
    ladders = {"pre-registered": [("C1", 32, 4), ("C1", 128, 16)], "exploratory": [("C1", 32, 4), ("C1", 32, 16)]}
    for lname, levels in ladders.items():
        for ds in DATASETS:
            cells = [C0] + levels + [("C2", c[1], c[2]) for c in levels]
            ids = sorted(set.intersection(*[set(idx[ds][c]) for c in cells]))
            g = {c: np.array([idx[ds][c][i]["correct"] for i in ids], bool) for c in cells}
            c0 = g[C0]
            l1, l2 = levels
            k1, k2 = ("C2", l1[1], l1[2]), ("C2", l2[1], l2[2])
            nfe1, nfe2 = 1 + (l1[2] + 1), 1 + (l1[2] + 1) + (l2[2] + 1)
            orc_correct = c0 | g[l1] | g[l2]
            orc_nfe = np.where(c0, 1, np.where(g[l1], nfe1, np.where(g[l2], nfe2, 1)))
            st1 = ~c0 & g[l1] & g[k1]
            st2 = ~c0 & ~st1 & g[l2] & g[k2]
            st_correct = c0 | st1 | st2
            st_nfe = np.where(c0, 1, np.where(st1, nfe1, np.where(st2, nfe2, 1)))

            def kept(ix, c0=c0, oc=orc_correct, sc=st_correct):
                head = oc[ix].mean() - c0[ix].mean()
                return (sc[ix].mean() - c0[ix].mean()) / head if head > 0 else np.nan

            share = kept(np.arange(len(ids)))
            lo, hi = boot(kept, len(ids))
            out["A1_oracle"][f"{lname}|{ds}"] = {"c0": float(c0.mean()), "oracle": float(orc_correct.mean()), "oracle_nfe": float(orc_nfe.mean()),
                                                 "stable": float(st_correct.mean()), "stable_nfe": float(st_nfe.mean()), "kept": share, "lo": lo, "hi": hi}
            L.append(f"| {lname} | {ds} | {f(c0.mean())} | {f(orc_correct.mean())} / {f(orc_nfe.mean(), 2)} | "
                     f"{f(st_correct.mean())} / {f(st_nfe.mean(), 2)} | {f(share)} [{f(lo)}, {f(hi)}] |")
    L.append("")

    # ---------------- A2 scratch states an answer
    L += ["## A2. Does the scratch state an answer?", "",
          "Regex for an explicit answer in `scratch_text` (\"answer is/answer: X\" with a letter, Yes/No, or the exact option text; "
          "\"option/choice X\"); last match wins. Agreement = stated answer equals the slot argmax.", ""]
    for ds in DATASETS:
        L += [f"### {ds}", "", "| cell | share states answer | agree w/ slot | acc (states / not) | mean conf (states / not) | ECE (states / not) |",
              "|---|---|---|---|---|---|"]
        for cell in CELLS13[1:]:
            group = list(idx[ds][cell].values())
            stated = [stated_answer(r.get("scratch_text", ""), items[r["item_id"]]) for r in group]
            has = np.array([s is not None for s in stated])
            agree = np.mean([s == r["pred"] for s, r in zip(stated, group) if s is not None]) if has.any() else float("nan")
            corr = np.array([r["correct"] for r in group], bool)
            cf = np.array([conf(r) for r in group])

            def split(mask):
                if mask.sum() == 0:
                    return None, None, None
                return float(corr[mask].mean()), float(cf[mask].mean()), expected_calibration_error(corr[mask], cf[mask])

            s_acc, s_conf, s_ece = split(has)
            n_acc, n_conf, n_ece = split(~has)
            out["A2"][f"{ds}|{name(cell)}"] = {"share": float(has.mean()), "agree": float(agree), "acc_states": s_acc, "acc_not": n_acc,
                                               "conf_states": s_conf, "conf_not": n_conf, "ece_states": s_ece, "ece_not": n_ece, "n_states": int(has.sum())}
            L.append(f"| {name(cell)} | {f(has.mean())} (n={int(has.sum())}) | {f(agree)} | {f(s_acc)} / {f(n_acc)} | {f(s_conf)} / {f(n_conf)} | {f(s_ece)} / {f(n_ece)} |")
        L.append("")

    # ---------------- A3 trajectories
    L += ["## A3. Confidence trajectory (mean top-1 prob by readout step; C1, T=16)", "",
          "Readout step t is read on forward pass t (before that pass unmasks); step 17 is the final read.", ""]
    steps_show = [1, 2, 3, 5, 9, 13, 16, 17]
    for scratch in (32, 128):
        L += [f"### C1 S={scratch} T=16", "", "| dataset | final | n | " + " | ".join(f"step {s}" for s in steps_show) + " |",
              "|---|---|---|" + "---|" * len(steps_show)]
        for ds in DATASETS:
            group = list(idx[ds][("C1", scratch, 16)].values())
            for label, want in (("correct", True), ("wrong", False)):
                sel = [r for r in group if r["correct"] == want]
                traj = [float(np.mean([max(r["readouts"][s - 1]["probs"].values()) for r in sel])) for s in range(1, 18)]
                out["A3"][f"S{scratch}|{ds}|{label}"] = {"n": len(sel), "mean_top1_by_step": traj}
                L.append(f"| {ds} | {label} | {len(sel)} | " + " | ".join(f(traj[s - 1]) for s in steps_show) + " |")
        L.append("")

    # ---------------- A4 AUROC
    L += ["## A4. Why H3 fails: can the C0 margin find the fixable items?", "",
          "Among items wrong at C0: label = C1(32,16) correct. Score = −(C0 top-2 margin), so AUROC > 0.5 means a smaller margin "
          "predicts a fix (what the escalation rule assumes). Also shown: AUROC of −margin for 'C0 wrong' among all items.", "",
          "| dataset | C0 wrong n | fixed by C1(32,16) | AUROC fix [CI] | AUROC C0-wrong (all items) [CI] |", "|---|---|---|---|---|"]
    for ds in DATASETS:
        base, tgt = idx[ds][C0], idx[ds][("C1", 32, 16)]
        ids = sorted(set(base) & set(tgt))
        m = np.array([margin(base[i]) for i in ids])
        c0 = np.array([base[i]["correct"] for i in ids], bool)
        fix = np.array([tgt[i]["correct"] for i in ids], bool)
        wrong = np.where(~c0)[0]
        a_fix = auroc(-m[wrong], fix[wrong])
        lo, hi = boot(lambda ix, w=wrong: auroc(-m[w][ix], fix[w][ix]), len(wrong))
        a_err = auroc(-m, ~c0)
        lo2, hi2 = boot(lambda ix: auroc(-m[ix], ~c0[ix]), len(ids))
        out["A4"][ds] = {"wrong_n": int(len(wrong)), "fixed": int(fix[wrong].sum()), "auroc_fix": a_fix, "lo": lo, "hi": hi,
                         "auroc_c0_wrong": a_err, "lo2": lo2, "hi2": hi2}
        L.append(f"| {ds} | {len(wrong)} | {int(fix[wrong].sum())} | {f(a_fix)} [{f(lo)}, {f(hi)}] | {f(a_err)} [{f(lo2)}, {f(hi2)}] |")
    L.append("")

    # ---------------- A5 LLaDA vs Qwen
    L += ["## A5. LLaDA C0 vs Qwen3-8B C0 (difference = LLaDA − Qwen)", "",
          "| dataset | n | Δacc [CI] (McNemar p) | ΔECE [CI] | ΔBrier [CI] | ΔNLL [CI] |", "|---|---|---|---|---|---|"]
    for ds in DATASETS:
        a_map, q_map = idx[ds][C0], qidx[ds][C0]
        ids = sorted(set(a_map) & set(q_map))
        A = [a_map[i] for i in ids]
        Q = [q_map[i] for i in ids]

        def metrics(rows_, ix):
            sel = [rows_[i] for i in ix]
            corr = [r["correct"] for r in sel]
            cf = [conf(r) for r in sel]
            probs = [[r["final_probs"][x] for x in r["final_probs"]] for r in sel]
            gold = [list(r["final_probs"]).index(r["gold"]) for r in sel]
            return (np.mean(corr), expected_calibration_error(corr, cf), multiclass_brier(probs, gold),
                    negative_log_likelihood([r["final_probs"][r["gold"]] for r in sel]))

        full = np.arange(len(ids))
        da = np.subtract(metrics(A, full), metrics(Q, full))
        rng = np.random.default_rng(SEED)
        bs = np.array([np.subtract(metrics(A, ix), metrics(Q, ix)) for ix in (rng.integers(0, len(ids), len(ids)) for _ in range(N_BOOT))])
        lo, hi = np.quantile(bs, 0.025, axis=0), np.quantile(bs, 0.975, axis=0)
        p = mcnemar_test([r["correct"] for r in A], [r["correct"] for r in Q])["p_value_exact"]
        out["A5"][ds] = {"n": len(ids), "diff": da.tolist(), "lo": lo.tolist(), "hi": hi.tolist(), "mcnemar_p": p,
                         "order": ["accuracy", "ece", "brier", "nll"]}
        L.append(f"| {ds} | {len(ids)} | {f(da[0])} [{f(lo[0])}, {f(hi[0])}] (p={f(p, 4)}) | {f(da[1])} [{f(lo[1])}, {f(hi[1])}] | "
                 f"{f(da[2])} [{f(lo[2])}, {f(hi[2])}] | {f(da[3])} [{f(lo[3])}, {f(hi[3])}] |")
    L.append("")

    (ROOT / "results" / "v13_exploratory.md").write_text("\n".join(L) + "\n", encoding="utf-8")
    (ROOT / "results" / "v13_exploratory.json").write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print("wrote results/v13_exploratory.md")


if __name__ == "__main__":
    main()
