"""Generate every LaTeX table in paper/tables/ from results files, and copy figures into paper/figs/.

No numbers are typed by hand: each table reads results/summary.csv, results/*.json, or
results/v13_*.json / v14_*.json. Run from the repo root:  python paper/make_tables.py
"""

from __future__ import annotations

import csv
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R = ROOT / "results"
T = ROOT / "paper" / "tables"
FIGS = ROOT / "paper" / "figs"
DATASETS = ["boolq", "strategyqa", "arc_c", "jagged"]
DSNAME = {"boolq": "BoolQ", "strategyqa": "StrategyQA", "arc_c": "ARC-C", "jagged": "Jagged"}
BS = "\\"
ABBR = {"supported": "met", "not supported": "failed", "inconclusive": "inconcl.", "not evaluated": "n/e"}


def f(x, d=3):
    try:
        return f"{float(x):.{d}f}"
    except (TypeError, ValueError):
        return "--"


def ci(est, lo, hi, d=3):
    return f"{f(est, d)} [{f(lo, d)}, {f(hi, d)}]"


def tex(s: str) -> str:
    return s.replace("_", BS + "_").replace("%", BS + "%").replace("&", BS + "&")


def write(name, caption, label, header, rows, source, size=BS + "small", fit=False, spec="t"):
    """One table environment. fit=True scales the tabular to the text width."""
    cols = "ll" + "r" * (len(header) - 2) if len(header) > 2 else "l" * len(header)
    nl = " " + BS + BS
    out = [f"% generated by paper/make_tables.py from {source}", BS + f"begin{{table}}[{spec}]", BS + "centering", size,
           BS + f"caption{{{caption}}}", BS + f"label{{{label}}}"]
    if fit:
        out.append(BS + "resizebox{" + BS + "linewidth}{!}{%")
    out += [BS + f"begin{{tabular}}{{{cols}}}", BS + "toprule", " & ".join(header) + nl, BS + "midrule"]
    out += [" & ".join(r) + nl for r in rows]
    out += [BS + "bottomrule", BS + "end{tabular}" + ("}" if fit else ""), BS + "end{table}", ""]
    (T / f"{name}.tex").write_text("\n".join(out), encoding="utf-8")


def main() -> None:
    T.mkdir(parents=True, exist_ok=True)
    FIGS.mkdir(parents=True, exist_ok=True)
    splits = json.loads((R / "splits.json").read_text(encoding="utf-8"))
    hyp = json.loads((R / "hypothesis_tests.json").read_text(encoding="utf-8"))

    # ---------------- main text
    write("tab_data", "Items per split. Test is the original (v1.1) test set plus seed-drawn additions registered before test (v1.2).",
          "tab:data", ["Dataset", "Dev", "Test", "Test (original)"],
          [[DSNAME[d], str(len(splits["datasets"][d]["dev"])), str(len(splits["datasets"][d]["test"])),
            str(len(splits["datasets"][d]["test_original"]))] for d in DATASETS], "results/splits.json")

    c = hyp["contrasts"]
    h1 = [x for x in c if x["hypothesis"] == "H1"]
    h2 = {x["dataset"]: x for x in c if x["hypothesis"] == "H2"}
    h4 = [x for x in c if x["hypothesis"] == "H4"]
    h3 = hyp["H3_per_dataset"]
    rows = [
        ["H1", "C1 ECE($T{=}16$) $-$ ECE($T{=}1$), 4 datasets $\\times$ $S\\in\\{32,128\\}$", hyp["H1"],
         f"{sum(x['lo'] > 0 for x in h1)}/{len(h1)} CIs $>0$", f"{f(min(x['estimate'] for x in h1))} to {f(max(x['estimate'] for x in h1))}"],
        ["H2", "Acc C1($S{=}128,T{=}16$) $-$ Acc C0", hyp["H2"],
         "; ".join(f"{DSNAME[d]} {ABBR[h2[d]['status']]}" for d in DATASETS),
         f"{f(min(x['estimate'] for x in h2.values()))} to {f(max(x['estimate'] for x in h2.values()))}"],
        ["H3", "Mean gap $G$, escalation curve vs fixed frontier", hyp["H3"],
         f"{sum(v['dominates'] for v in h3.values())}/{len(h3)} dominate",
         f"{f(min(v['G'] for v in h3.values()))} to {f(max(v['G'] for v in h3.values()))}"],
        ["H4", "C1 $-$ C2 (Acc, ECE) at $S{=}128$, $T{=}16$", hyp["H4"],
         f"{sum(x['status'] == 'supported' for x in h4)}/{len(h4)} CIs exclude 0",
         f"{f(min(x['estimate'] for x in h4))} to {f(max(x['estimate'] for x in h4))}"],
    ]
    write("tab_hyp_summary", "Pre-registered hypotheses (LLaDA-8B-Instruct, test set). Full contrasts in Appendix Table~" + BS + "ref{tab:hypotheses}.",
          "tab:hyp_summary", ["H", "Contrast", "Verdict", "Calls", "Estimate range"], rows, "results/hypothesis_tests.json", fit=True)
    (T / "verdicts.tex").write_text("% generated from results/hypothesis_tests.json\n" + "".join(
        BS + f"newcommand{{{BS}verdictH{w}}}{{{hyp[k]}}}\n"  # LaTeX macro names cannot contain digits
        for k, w in (("H1", "one"), ("H2", "two"), ("H3", "three"), ("H4", "four"))), encoding="utf-8")

    bc = json.loads((R / "v13_bc.json").read_text(encoding="utf-8"))
    tables = bc["C"]["tables"]
    rows = []
    for d in DATASETS:
        r = [DSNAME[d]]
        for cell in ("C0", "C1 32,1", "C1 32,16", "C2 32,16"):
            m = tables[f"{d}|{cell}"]
            r.append(f"{f(m['accuracy'])} / {f(m['ece'])}")
        rows.append(r)
    write("tab_dream_compact", "Dream-v0-Instruct-7B (exploratory, original test items): accuracy / ECE for C0 and selected $S{=}32$ cells. "
          "Full table in Appendix Table~" + BS + "ref{tab:dream}.", "tab:dream_compact",
          ["Dataset", "C0", "C1 $T{=}1$", "C1 $T{=}16$", "C2 $T{=}16$"], rows, "results/v13_bc.json")

    # ---------------- appendix
    summary = list(csv.DictReader((R / "summary.csv").open(encoding="utf-8")))
    for d in DATASETS:
        rows = []
        for r in summary:
            if r["dataset"] != d:
                continue
            name = "Qwen3-8B C0" if r["model"].startswith("qwen") else r["cell"]
            rows.append([tex(name), f(r["accuracy"]), f(r["ece"]), f(r["adaptive_ece"]), f(r["ece_ts_pooled"]),
                         f(r["ece_ts_dataset"]), f(r["off_label_mass"]), f(r["nfe"], 0)])
        write(f"tab_main_{d}", f"{DSNAME[d]} test results (LLaDA-8B-Instruct cells and Qwen3-8B C0).", f"tab:main_{d}",
              ["Cell", "Acc", "ECE", "aECE", "ECE-TS pool", "ECE-TS ds", "Off-label", "NFE"], rows, "results/summary.csv", spec="h!")

    def call(x):
        # H2 BoolQ/ARC-C predict no gain, so "supported" means the prediction held; H1-accuracy is descriptive.
        if x["hypothesis"] == "H2" and x["dataset"] in ("boolq", "arc_c") and x["status"] == "supported":
            return "as predicted (no gain)"
        if x["hypothesis"] == "H1-accuracy":
            return "positive" if x["lo"] > 0 else "negative" if x["hi"] < 0 else "inconclusive"
        return x["status"]

    rows = []
    for x in c:
        mc = x.get("mcnemar") or {}
        rows.append([x["hypothesis"], DSNAME.get(x["dataset"], str(x["dataset"])), tex(x["description"]),
                     ci(x.get("estimate"), x.get("lo"), x.get("hi")), f(mc.get("p_value_exact"), 4) if mc else "--", call(x)])
    write("tab_hypotheses", "All pre-registered contrasts (paired bootstrap, 1000 resamples, 95\\% CI; McNemar exact).",
          "tab:hypotheses", ["H", "Dataset", "Contrast", "Estimate [CI]", "McNemar p", "Call"], rows, "results/hypothesis_tests.json",
          BS + "scriptsize", fit=True, spec="h!")
    write("tab_h3", "H3: mean gap $G$ between the escalation curve and the running-max fixed frontier.", "tab:h3",
          ["Dataset", "n", "G [CI]", "Min gap", "Max gap", "Dominates"],
          [[DSNAME[d], str(h["n"]), ci(h["G"], h["lo"], h["hi"], 4), f(h["min_gap"]), f(h["max_gap"]), str(h["dominates"])]
           for d, h in hyp["H3_per_dataset"].items()], "results/hypothesis_tests.json", spec="h!")

    esc = json.loads((R / "escalation_test.json").read_text(encoding="utf-8"))
    rows = []
    for ladder, block in esc["ladders"].items():
        for d, e in block["datasets"].items():
            fz, orc, h = e["frozen_tau"] or {}, e["oracle"], e["h3_statistic"]
            rows.append([{"preregistered": "pre-registered"}.get(ladder, ladder), DSNAME[d], ci(h["G"], h["lo"], h["hi"], 4), f"{f(fz.get('accuracy'))} / {f(fz.get('mean_nfe'), 2)}",
                         f"{f(orc['accuracy'])} / {f(orc['mean_nfe'], 2)}"])
    write("tab_escalation", "Escalation ladders: full-curve gap, frozen-$\\tau$ point, and oracle (accuracy / mean NFE).",
          "tab:escalation", ["Ladder", "Dataset", "G [CI]", "Frozen $\\tau$", "Oracle"], rows, "results/escalation_test.json", spec="h!")

    abl = json.loads((R / "noeos_ablation_test.json").read_text(encoding="utf-8"))
    write("tab_noeos", "Suppressing end tokens in scratch at $S{=}128$ (original test items): ON minus OFF.", "tab:noeos",
          ["Dataset", "Cell", "$\\Delta$Acc [CI]", "$\\Delta$ECE [CI]", "EOS frac off$\\to$on"],
          [[DSNAME[a["dataset"]], a["cell"], ci(a["acc_diff"], a["acc_lo"], a["acc_hi"]), ci(a["ece_diff"], a["ece_lo"], a["ece_hi"]),
            f"{f(a['eos_off_median'])}$\\to${f(a['eos_on_median'])}"] for a in abl], "results/noeos_ablation_test.json",
          BS + "scriptsize", fit=True, spec="h!")

    rows = []
    for k, v in bc["B"]["contrasts"].items():
        d, cond, kind, which = k.split("|")
        rows.append([DSNAME[d], cond, f"{'ECE' if kind == 'ece' else kind} {which}", ci(v["estimate"], v["lo"], v["hi"], 4), v["call"]])
    write("tab_t32", "LLaDA at $S{=}32$: $T{=}32$ vs $T{=}1$ and vs $T{=}16$ (original test items; exploratory).", "tab:t32",
          ["Dataset", "Cond", "Contrast", "Estimate [CI]", "CI"], rows, "results/v13_bc.json", BS + "scriptsize", spec="h!")
    rows = [[DSNAME[k.split("|")[0]], k.split("|")[1], f(m["accuracy"]), f(m["ece"]), f(m["ece_ts"]), f(m["nfe"], 0)] for k, m in tables.items()]
    write("tab_dream", "Dream-v0-Instruct-7B on the original test items (exploratory).", "tab:dream",
          ["Dataset", "Cell", "Acc", "ECE", "ECE-TS", "NFE"], rows, "results/v13_bc.json", BS + "scriptsize", spec="h!")
    rows = [[DSNAME[k.split("|")[0]], k.split("|")[1], ci(v["estimate"], v["lo"], v["hi"], 4), v["call"]] for k, v in bc["C"]["contrasts"].items()]
    write("tab_dream_contrasts", "Dream: H1-style and H4-style contrasts (exploratory).", "tab:dream_contrasts",
          ["Dataset", "Contrast", "Estimate [CI]", "CI"], rows, "results/v13_bc.json", BS + "scriptsize", spec="h!")

    ex = json.loads((R / "v13_exploratory.json").read_text(encoding="utf-8"))
    rows = [[DSNAME[k.split("|")[0]], k.split("|")[1], str(v["w2r"]), str(v["r2w"]), ci(v["net"], v["lo"], v["hi"])] for k, v in ex["A1"].items()]
    write("tab_flips", "Flips relative to C0 (LLaDA, test): wrong$\\to$right, right$\\to$wrong, net (exploratory).", "tab:flips",
          ["Dataset", "Cell", "W$\\to$R", "R$\\to$W", "Net [CI]"], rows, "results/v13_exploratory.json", BS + "scriptsize", spec="h!")
    rows = [[k.split("|")[0], DSNAME[k.split("|")[1]], f(v["oracle"]), f(v["stable"]), ci(v["kept"], v["lo"], v["hi"])] for k, v in ex["A1_oracle"].items()]
    write("tab_oracle_stability", "Oracle headroom kept when escalation must be correct in both C1 and C2 (exploratory).", "tab:oracle_stability",
          ["Ladder", "Dataset", "Oracle acc", "Stable acc", "Share kept [CI]"], rows, "results/v13_exploratory.json", spec="h!")
    rows = [[DSNAME[d], str(v["wrong_n"]), str(v["fixed"]), ci(v["auroc_fix"], v["lo"], v["hi"]), ci(v["auroc_c0_wrong"], v["lo2"], v["hi2"])]
            for d, v in ex["A4"].items()]
    write("tab_margin_auroc", "AUROC of $-$(C0 top-2 margin): fixable items among C0 errors, and C0 errors overall (exploratory).",
          "tab:margin_auroc", ["Dataset", "C0 wrong", "Fixed", "AUROC fix [CI]", "AUROC error [CI]"], rows, "results/v13_exploratory.json", spec="h!")

    v14 = json.loads((R / "v14_exploratory.json").read_text(encoding="utf-8"))
    rows_a, rows_b = [], []
    for key, block in v14.items():
        if not (key.startswith("B1|") or key.startswith("B2|")):
            continue
        pair = tex(key.split("|", 1)[1])
        for d, r in block.items():
            g = lambda m: ci(r["diff"][m], r["lo"][m], r["hi"][m])  # noqa: E731
            rows_a.append([pair, DSNAME[d], g("acc"), g("ECE"), g("aECE")])
            rows_b.append([pair, DSNAME[d], g("Brier"), g("NLL"), g("ECE-TS(own)")])
    write("tab_onepass_a", "One-pass (C0) comparisons on the original test items, A minus B: accuracy and calibration (exploratory).",
          "tab:onepass_a", ["A $-$ B", "Dataset", "$\\Delta$Acc", "$\\Delta$ECE", "$\\Delta$aECE"], rows_a,
          "results/v14_exploratory.json", BS + "scriptsize", fit=True, spec="h!")
    write("tab_onepass_b", "One-pass (C0) comparisons on the original test items, A minus B: proper scores and ECE after each model's own temperature (exploratory).",
          "tab:onepass_b", ["A $-$ B", "Dataset", "$\\Delta$Brier", "$\\Delta$NLL", "$\\Delta$ECE-TS"], rows_b,
          "results/v14_exploratory.json", BS + "scriptsize", fit=True, spec="h!")
    rows = []
    for key in ("B3|LLaDA", "B3|Dream"):
        for d, cnt in v14[key]["counts"].items():
            rows.append([key.split("|")[1], DSNAME[d], f"{cnt['above_zero']} / {cnt['cells']}"])
    write("tab_anythinking", "Cells whose ECE exceeds C0's (CI above 0): any scratch vs none (exploratory).", "tab:anythinking",
          ["Model", "Dataset", "Cells CI $>0$"], rows, "results/v14_exploratory.json", spec="h!")

    for png in sorted((R / "figs").glob("*_test.png")) + [R / "figs" / "dev_escalation.png"]:
        if png.exists():
            shutil.copy2(png, FIGS / png.name)
    for old in ("tab_onepass.tex",):
        (T / old).unlink(missing_ok=True)
    print("tables:", sorted(p.name for p in T.glob("*.tex")))


if __name__ == "__main__":
    main()
